### ISSUE TITLE
Great Example! One small thing

### ISSUE THREAD

**Issue by PGMacDesign** [jacktech24/gcmnetworkmanager-android-example#2]
Love the example, very easy to use and very easy to understand. 

One small problem I seem to be having and I am unsure as to whether or not I transposed the code incorrectly or if there is an inherent problem, whenever I call the 2 cacnel methods (cancelOneOff / cancelRepeat) it does fire (my log statements confirm it), but then I still get toasts a bit afterwords that REPEATING has executed. Shouldn't the cancelTask stop those? Or am I misunderstanding?

Thanks again for the example!

-PGMacD

**Comment by filipproch** [comment]
@PGMacDesign I will look into it, but you should also execute the ADB command to check whether the tasks were really canceled, to find out where is the problem

```
adb shell dumpsys activity service GcmService --endpoints DataUpdateService
```

**Comment by filipproch** [comment]
@PGMacDesign For me (tested on two phones, Kitkat and Lollipop), it is working as expected with the example code in this repository - when I click cancel oneoff, the toast won't show up

what is your development configuration and have you tried debugging it with the command above?

**Comment by PGMacDesign** [comment]
@jacktech24  , I will give that adb shell command a test tomorrow evening. For now, thanks for taking the time to investigate it! Likely something wrong on my end then, but I will update ya here once I have results.
-Sil
