### ISSUE TITLE
Works only charging mode changed

### ISSUE THREAD

**Issue by TunaYagci** [jacktech24/gcmnetworkmanager-android-example#3]
I got this weird bug on 4.4.2(KitKat) version. Same code works like magic in Lolipop but KitKat has this weird bug. I just don't understand. Problem is, as I explained on title, onRunTask works only when "charging mode changed to charging again" on repeating mode.

Code I'm using is yours, except:
"setRequiresCharing(false)" and "setRequiredNetwork(Task.NETWORK_STATE_ANY)"

It's like there is an invisible intent-filter for charging and it makes onRunTask run. I'm pretty confused about this API and considering moving back to AlarmManager.

**Comment by filipproch** [comment]
@MyHeartsECO at first, if I understand your issue, you have setRequiresCharing(true) and your onRunTask is called only when charging state changes (aka. device is pluggen into charger)?
this could be bug in GcmNetworkManager and you should report it on apps-help@google.com

**Comment by TunaYagci** [comment]
@jacktech24 yes, but setRequiresCharging is set to "false"; and, exactly when I plugged to device back into charger, it runs onRunTask. 

I wonder if you can try your code on a KitKat or any pre-Lolipop device. I want to be sure that if problem is because of me or not before reporting this issue to Google.

Thanks for replying!

**Comment by filipproch** [comment]
@MyHeartsECO tested on 4.4.4 kitkat Samsung device, not seeing your behaviour, running the same code as in this repo

**Comment by TunaYagci** [comment]
@jacktech24 okay then, I'm gonna report that.
